### ISSUE TITLE
the mirror repo rewrites every time due to the different branch name from `master`

### ISSUE THREAD

**Issue by bekcpear** [mgorny/repo-mirror-ci#5]
Like these commits: https://github.com/gentoo-mirror/ryans/commits/master

There are very much same commit messages, "Merge/replace with the new version of main (reversed 'ours' strategy)".

I check the code, found https://github.com/mgorny/repo-mirror-ci/blob/f01a4d828a0263f4adc97c4c8a6c869c04314937/repos/smart-merge.bash#L19

This line always use the sync-repo's branch name to compare with the new created branch, and it will cause if the branch name of sync-repo is not `master` (the `m_branch` value), the command is executed failed and the mirror-repo will be rewritten in [Line47-53](https://github.com/mgorny/repo-mirror-ci/blob/f01a4d828a0263f4adc97c4c8a6c869c04314937/repos/smart-merge.bash#L47-L53).

I'm not sure if it can be fixed by changing first `${branch}` to `${m_branch}` in [L19](https://github.com/mgorny/repo-mirror-ci/blob/f01a4d828a0263f4adc97c4c8a6c869c04314937/repos/smart-merge.bash#L19)

**Comment by mgorny** [comment]
Thanks for the report. This indeed sucks. I can't look into it right now, so I'm just going to blacklist the affected repos.

**Comment by mgorny** [comment]
Hmm, you're probably right as to the solution. I'm going to try to test it later today.

**Comment by mgorny** [comment]
I'm deploying the suggested fix and reenabling ryans repo for testing. If it works, I'll reenable all of them.

**Comment by mgorny** [comment]
Ok, it seems that things are working now and so far nothing weird has happened. Please reopen (or ping me if you can't reopen) if you notice anything strange again.
